<div class="container page-content">
  <h1>Bild hochladen</h1>
  <form method="post" enctype="multipart/form-data">
    <div class="form-group">
      <label for="images">Bild(er)</label>
      <input type="file" multiple="multiple" accept="image/*" id="images" name="images[]">
    </div>
    <div class="form-group">
      <label for="tags">Tags</label>
      <input class="form-control" placeholder="Ferien, Italien ..." type="text" id="tags" name="tags">
    </div>

    <button type="submit" class="btn btn-primary">Speichern</button>
    <a href="/galery/1" class="btn btn-default">Abbrechen</a>
  </form>
</div>
