<div class="container page-content">
  <h1>
    <?php echo $this->galery->name; ?>
    <a href="/galery/<?php echo $this->galery->id; ?>/edit"   class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-pencil"></span></a>
    <a href="/galery/<?php echo $this->galery->id; ?>/delete" class="btn btn-danger  btn-xs"><span class="glyphicon glyphicon-trash"></span></a>
  </h1>
  <div class="search">
    <form method="get" class="form-inline">
      <select class="form-control" name="tag">
        <?php
          foreach ($this->tags as $tag) {
            echo sprintf('<option value="%d">%s</option>', $tag->id, $tag->name);
          }
        ?>
        <option>
      </select>
      <button type="submit" class="btn btn-primary">Filtern</button>
    </form>
  </div>
  <div class="image-list">
    <?php
      foreach ($this->images as $image) {
        echo sprintf('<div class="image-item"><img src="%s"></div>', $image->getThumbnailUrl());
      }
    ?>
    <a class="image-item image-item-upload" href="/galery/1/upload">
      <span class="glyphicon glyphicon-cloud-upload"></span>
    </a>
  </div>
</div>

<!-- add this in js
<div class="lightbox">
  <div class="lightbox-container container">
    <span class="lightbox-close glyphicon glyphicon-remove-circle"></span>
    <div class="lightbox-image">
      <span class="lightbox-prev glyphicon glyphicon-chevron-left"></span>
      <img src="http://placekitten.com/1920/1080">
      <span class="lightbox-next glyphicon glyphicon-chevron-right"></span>
    </div>
    <div class="lightbox-tags">
      <div class="tag">image</div>
      <div class="tag">fun</div>
      <div class="tag">whatever</div>
    </div>
  </div>
</div>
-->
