<div class="container page-content">
  <h1>
    <?php echo htmlspecialchars($this->galery->name); ?>
    <a href="/galery/<?php echo $this->galery->id; ?>/edit"   class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-pencil"></span></a>
    <a href="/galery/<?php echo $this->galery->id; ?>/delete" class="btn btn-danger  btn-xs"><span class="glyphicon glyphicon-trash"></span></a>
  </h1>
  <div class="search">
    <form method="get" class="form-inline">
      <select class="form-control" name="tag">
        <option></option>
        <?php
          foreach ($this->tags as $tag) {
            echo sprintf(
              '<option value="%d" %s>%s</option>',
              $tag->id,
              $tag->id === $this->tag ? 'selected' : '',
              htmlspecialchars($tag->name)
            );
          }
        ?>
      </select>
      <button type="submit" class="btn btn-primary">Filtern</button>
    </form>
  </div>
  <div class="image-list">
    <?php
      foreach ($this->images as $image) {
        echo sprintf('<a href="%s" class="image-item"><div class="tags">', $image->getUrl());
        foreach ($image->tags as $tag) {
          echo sprintf('<span class="label label-default">%s</span>', htmlspecialchars($tag->name));
        }
        echo sprintf('</div><button onclick="location.href = \'/image/%s/delete\'" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-trash"></span></button>', $image->id);
        echo sprintf('<img src="%s"></a>', $image->getThumbnailUrl());
      }
    ?>
    <a class="image-item image-item-upload" href="/galery/<?php echo $this->galery->id; ?>/upload">
      <span class="glyphicon glyphicon-cloud-upload"></span>
    </a>
  </div>
</div>
