<div class="container page-content">
  <h1>Galerie löschen</h1>
  <?php $this->outputErrors(); ?>
  <form method="post">
    <p>
      Wollen Sie die Galerie '<?php echo htmlspecialchars($this->galery->name); ?>' wirklich löschen?
    </p>

    <button type="submit" class="btn btn-danger">Löschen</button>
    <a href="/galery/<?php echo $this->galery->id; ?>" class="btn btn-default">Abbrechen</a>
  </form>
</div>
