<div class="container page-content">
  <h1>Galerie '<?php echo htmlspecialchars($this->galery->name); ?>' bearbeiten</h1>
  <?php $this->outputErrors(); ?>
  <form method="post">
    <div class="form-group">
      <label for="name">Name</label>
      <input required class="form-control" type="text" id="name" name="name" value="<?php echo $this->galery->name ?>">
    </div>
    <div class="form-group">
      <label>
        <input type="checkbox" name="public" <?php if ($this->galery->public) { echo 'checked'; } ?>> Öffentlich
      </label>
    </div>

    <button type="submit" class="btn btn-primary">Speichern</button>
    <a href="/" class="btn btn-default">Abbrechen</a>
  </form>
</div>
