<div class="container page-content">
  <h1>Galerie erstellen</h1>
  <?php $this->outputErrors(); ?>
  <form method="post">
    <div class="form-group">
      <label for="name">Name</label>
      <input class="form-control" type="text" id="name" name="name">
    </div>
    <div class="form-group">
      <label>
        <input type="checkbox" name="public"> Öffentlich
      </label>
    </div>

    <button type="submit" class="btn btn-primary">Speichern</button>
    <a href="/" class="btn btn-default">Abbrechen</a>
  </form>
</div>
