<div class="login">
  <form method="post">
    <div class="panel panel-default panel-login">
      <div class="panel-heading">
        <div class="logo">
          <span class="glyphicon glyphicon-camera"></span>
        </div>
        <h1>Login</h1>
      </div>
      <div class="panel-body">
        <?php $this->outputErrors(); ?>
        <div class="form-group">
          <input class="form-control" type="email" placeholder="Email" name="email">
        </div>
        <div class="form-group">
          <input class="form-control" type="password" placeholder="Password" name="password">
        </div>
        <div class="checkbox form-group">
          <label>
            <input type="checkbox" name="keep">
            Eingeloggt bleiben (30 Tage)
          </label>
        </div>
        <div class="form-group">
          <button class="btn btn-primary" type="submit"><span class="glyphicon glyphicon-on"></span> Login</button>
        </div>
        Du hast noch keinen Account? Hier <a href="/register">registrieren</a>
      </div>
    </div>
  </form>
  <div class="copyrights">&copy; 2016 Jonas Metzener</div>
</div>
