<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-camera"></span></a>
    </div>
    <div class="collapse navbar-collapse navbar-right" id="nav-collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-camera"></span> Galerien <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/"><span class="glyphicon glyphicon-home"></span> Eigene</a></li>
            <li><a href="/public"><span class="glyphicon glyphicon-cloud"></span> Öffentliche</a></li>
          </ul>
        </li>
        <li><a href="/settings"><span class="glyphicon glyphicon-cog"></span> Einstellungen</a></li>
        <li><a href="/logout"><span class="glyphicon glyphicon-off"></span> Logout</a></li>
      </ul>
    </div>
  </div>
</nav>
