<div class="login">
  <form method="post">
    <div class="panel panel-default panel-login">
      <div class="panel-heading">
        <div class="logo">
          <span class="glyphicon glyphicon-camera"></span>
        </div>
        <h1>Registrieren</h1>
      </div>
      <div class="panel-body">
        <?php $this->outputErrors(); ?>
        <div class="form-group">
          <input class="form-control" type="email" placeholder="Email" name="email">
        </div>
        <div class="form-group">
          <input class="form-control" type="password" placeholder="Password" name="password">
        </div>
        <div class="form-group">
          <input class="form-control" type="password" placeholder="Password wiederholen" name="password2">
        </div>
        <div class="form-group">
          <button class="btn btn-primary" type="submit">Registrieren</button>
        </div>
        Du hast bereits einen Account? Hier <a href="/login">einloggen</a>
      </div>
    </div>
  </form>
  <div class="copyrights">&copy; 2016 Jonas Metzener</div>
</div>
