<div class="container page-content">
  <h1>Accountdaten bearbeiten</h1>
  <form method="post" autocomplete="off">
    <div class="form-group">
      <label for="email">Email</label>
      <input class="form-control" type="email" id="email" name="email" value="<?php echo $this->user->email ?>">
    </div>
    <div class="form-group">
      <label for="passwordold">Altes Passwort</label>
      <input class="form-control" type="password" id="passwordold" name="passwordold">
    </div>
    <div class="form-group">
      <label for="password">Neues Passwort</label>
      <input class="form-control" type="password" id="password" name="password">
    </div>
    <div class="form-group">
      <label for="password2">Neues Passwort wiederholen</label>
      <input class="form-control" type="password" id="password2" name="password2">
    </div>

    <button type="submit" class="btn btn-primary">Speichern</button>
    <a href="/settings/delete" class="btn btn-danger">Account löschen</a>
  </form>
</div>
